const assert = require("assert");
const fs = require("fs");
const path = require("path");
const vm = require("vm");

const root = path.resolve(__dirname, "..");
const html = fs.readFileSync(path.join(root, "web", "index.html"), "utf8");
const js = fs.readFileSync(path.join(root, "web", "app.js"), "utf8");
const css = fs.readFileSync(path.join(root, "web", "styles.css"), "utf8");
const bat = fs.readFileSync(path.join(root, "web", "start-web.bat"), "utf8");
const data = fs.readFileSync(path.join(root, "web", "data.js"), "utf8");
const dataContext = { window: {} };
vm.runInNewContext(data, dataContext);
const webCatalogs = dataContext.window.__QUOTE_CATALOGS__;

assert.ok(html.includes("data-start-quote=\"dealer\""));
assert.ok(html.includes("data-start-quote=\"channel\""));
assert.ok(html.includes("id=\"exportImageBtn\""));
assert.ok(html.includes("id=\"exportPreview\""));
assert.ok(html.includes("id=\"exportPreviewImage\""));
assert.ok(html.includes("id=\"summaryRemark\""));
assert.ok(html.includes("id=\"quoteCategoryTabs\""));
assert.ok(html.includes("../assets/interior-bg.jpg"));
assert.ok(html.includes("./data.js"));
assert.ok(html.includes("./app.js"));

assert.ok(js.includes("createCjsLoader"));
assert.ok(js.includes("utils/catalogs.js"));
assert.ok(js.includes("window.__QUOTE_CATALOGS__"));
assert.ok(js.includes("canvas.toDataURL(\"image/png\")"));
assert.ok(js.includes("MicroMessenger"));
assert.ok(js.includes("showExportPreview(imageUrl)"));
assert.ok(js.includes("function drawQuoteWatermark(ctx, width, height)"));
assert.ok(js.includes("新材联·New Material Union"));
assert.ok(js.includes('ctx.font = "bold 22px Microsoft YaHei, sans-serif"'));
assert.ok(js.includes("ctx.rotate(-24 * Math.PI / 180)"));
assert.ok(js.includes("const extent = Math.hypot(width, height)"));
assert.ok(js.includes("ctx.translate(width / 2, height / 2)"));
assert.ok(js.includes("ctx.save()"));
assert.ok(js.includes("ctx.restore()"));
assert.ok(js.includes("ctx.globalAlpha = 0.06"));
assert.ok(js.includes("drawQuoteWatermark(ctx, canvas.width, canvas.height)"));
assert.ok(js.includes("state.remark"));
assert.ok(js.includes("注意事项"));
assert.ok(js.includes("CUSTOM_TINTING_PRODUCT_ID"));
assert.ok(js.includes("data-action=\"custom-price\""));
assert.ok(js.includes("data-action=\"reference-color\""));
assert.ok(js.includes("参考颜色及色号"));
assert.ok(js.includes("referenceColor: referenceColorInput ? referenceColorInput.value.trim() : \"\""));
assert.ok(js.includes("referenceColorInput.value = addedProduct.referenceColor || \"\""));
assert.ok(js.includes("event.target.dataset.action === \"reference-color\""));
assert.ok(js.includes("syncCustomTintingFee"));
assert.ok(js.includes("function formatCoverage(option)"));
assert.ok(js.includes("function formatQuoteItemName(item)"));
assert.ok(js.includes("name: formatQuoteItemName(item)"));
assert.ok(js.includes("coverageText: formatCoverage(option)"));
assert.ok(js.includes("formatCoverage(product)"));
assert.ok(js.includes("quoteOpenCategories"));
assert.ok(js.includes("data-quote-category-target"));
assert.ok(js.includes("`${item.id}|${item.spec || item.selectedSpec || \"\"}`"));
assert.ok(js.includes("渠道合作单价"));

assert.ok(data.includes("window.__QUOTE_CATALOGS__"));
assert.ok(data.includes("\"dealer\""));
assert.ok(data.includes("\"channel\""));
assert.ok(data.includes("\"specOptions\""));
assert.ok(!data.includes("\"model\": \"DT-107\""));
const dealerFemaProducts = webCatalogs.dealer.filter((item) => item.category === "菲玛");
const channelFemaProducts = webCatalogs.channel.filter((item) => item.category === "菲玛");
const dealerLiquidTiles = webCatalogs.dealer.filter((item) => item.category === "液态瓷砖");
const channelLiquidTiles = webCatalogs.channel.filter((item) => item.category === "液态瓷砖");
assert.deepStrictEqual(Array.from(dealerFemaProducts, (item) => item.model), ["FEMA-001", "FEMA-002", "FEMA-003", "FEMA-004"]);
assert.deepStrictEqual(Array.from(dealerFemaProducts, (item) => item.dealerPrice), [350, 265, 295, 336]);
assert.deepStrictEqual(Array.from(channelFemaProducts, (item) => item.dealerPrice), [420, 318, 354, 403]);
assert.deepStrictEqual(Array.from(dealerLiquidTiles, (item) => item.model), ["DP-1021", "DP-1022", "DP-1023"]);
assert.deepStrictEqual(Array.from(dealerLiquidTiles, (item) => item.dealerPrice), [56, 56, 308]);
assert.deepStrictEqual(Array.from(channelLiquidTiles, (item) => item.dealerPrice), [67, 67, 370]);
assert.deepStrictEqual(Array.from(dealerLiquidTiles, (item) => item.coverage), ["未提供", "未提供", 3.5]);

assert.ok(css.includes(".quote-card.is-added"));
assert.ok(css.includes(".spec-select"));
assert.ok(css.includes(".quote-controls"));
assert.ok(css.includes(".quote-category-tabs"));
assert.ok(css.includes(".quote-category-panel.is-open .quote-category-body"));
assert.ok(css.includes("grid-template-columns: 1fr"));
assert.ok(css.includes("grid-template-columns: 42px minmax(56px, 1fr) 42px"));
assert.ok(css.includes(".export-preview.is-open"));
assert.ok(css.includes(".sheet-remark"));
assert.ok(css.includes(".summary-remark-control"));
assert.ok(css.includes(".custom-price-control"));
assert.ok(css.includes(".custom-reference-control"));
assert.ok(css.includes("grid-template-columns: minmax(106px, 34%) minmax(0, 1fr)"));
assert.ok(css.includes(".sheet-top"));
assert.ok(css.includes("@media (max-width: 720px)"));

assert.ok(bat.includes("start \"\" \"%~dp0index.html\""));
assert.ok(!bat.includes("http.server"));

console.log("web static app ok");
